name: Build Android NDK Project

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e # Versi NDK yang lebih tua seringkali lebih kompatibel dengan proyek lama

    - name: Compile with ndk-build
      run: |
        # Masuk ke folder jni karena di sanalah Android.mk berada
        cd jni
        # Jalankan ndk-build
        $ANDROID_NDK_HOME/ndk-build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-libraries
        path: |
          libs/**/*.so
